- name: Подмена веб-страницы
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  notify: "Nginx Reloader"
  when: "'proxy' in inventory_hostname" #Выполняем только на машинах, где в имени есть proxy