linux:
  children:
    nginx_proxy:
      hosts:
        <имя машины>-proxy:
          ansible_host: <адрес машины>
    nginx_custom:
      hosts:
        <имя машины>-custom:
          ansible_host: <адрес машины>
        <имя машины>-custom:
          ansible_host: <адрес машины>
  vars:
    ansible_user: "<юзер из тераформа>"
    connection_protocol: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519