- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  notify: "Nginx Reloader"
  when: "'custom' in inventory_hostname" #Выполняем только на машинах, где в имени есть custom